name: Deploy to Bunny.net

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0' # chọn version phù hợp

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy to Bunny Storage via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: sg.storage.bunnycdn.com
          username: bl1d
          password: ${{ secrets.BUNNY_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./public
          server-dir: /bl1d/
          log-level: verbose
