name: Deploy Hugo to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'

      - name: Build Hugo
        run: hugo --gc --minify --baseURL "https://bl1d.codeberg.page/"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Deploy to Codeberg
        run: |
          cd public
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git branch -M main
          git remote add origin git@codeberg.org:bl1d/pages.git
          git push --force origin main